version: '3.8'

services:
  gateway:
    image: nginx:alpine
    ports:
      - "${TEAM_PORT}:80"
    volumes:
      - ./gateway.conf:/etc/nginx/conf.d/default.conf:ro
      - ./staticfiles:/usr/src/app/team7/staticfiles
    depends_on:
      - team7_service
    environment:
      - CORE_BASE_URL=http://core:8000
    networks:
      - app404

  team7_service:
    build: .
    command: sh -c "python team7/manage.py collectstatic --noinput && gunicorn team7.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - .:/usr/src/app/team7
      - ../core:/usr/src/app/core
      - ./staticfiles:/usr/src/app/team7/staticfiles
    expose:
      - "8000"
    env_file:
      - .env
    environment:
      - CORE_BASE_URL=http://core:8000
      - DJANGO_SETTINGS_MODULE=team7.settings
      - PYTHONPATH=/usr/src/app
    networks:
      - app404

networks:
  app404:
    external: true
    name: app404_net
