services:
  gateway:
    image: nginx:alpine
    container_name: team14_gateway
    ports:
      - "80:80"
    volumes:
      - ./gateway.conf:/etc/nginx/conf.d/default.conf:ro
      - ../staticfiles:/staticfiles:ro
      - ../media:/media:ro
    depends_on:
      - team14_service
    networks:
      - app404


  team14_service:
    build:
      context: ..
      dockerfile: team14/Dockerfile
    container_name: team14_service
    expose:
      - "8000"
    networks:
      - app404

networks:
  app404:
    external: true
    name: app404_net
