services:
  team14_gateway:
    image: nginx:alpine
    container_name: team14_gateway
    ports:
      - "8014:80"  # پورت یونیک برای تیم 14
    volumes:
      - ./gateway.conf:/etc/nginx/conf.d/default.conf:ro
      - ../staticfiles:/staticfiles:ro
      - ../media:/media:ro
    networks:
      - app404

networks:
  app404:
    external: true
    name: app404_net
